# The MIT License
#
# Copyright 2021 Dara Meaney
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Using the cp4s_get_open_cases module to make a request for all open cases
- name: Retrieve a list of open cases
  cp4s_get_open_cases:
  register: open_cases

# Looping through the register which contains the open cases & printing out the ID & Name
- name: Print out list of open cases
  debug:
    msg:
      - "open_cases"
      - "ID: {{ item.id }}"
      - "Name: {{ item.name }}"
  loop: "{{ open_cases.case }}"
  loop_control:
    label: "{{ item.id }}"